---
title: C26111
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 5541ec5dcc8ccd55fe5288265090e3d9c5958e04
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 04/23/2019
ms.locfileid: "62550180"
---
# <a name="c26111"></a>C26111
Advertencia C26111: Llamador no desbloquear \<bloqueo > antes de llamar a la función \<func >.

 La anotación `_Requires_lock_not_held_` impone una condición previa que el recuento de bloqueos del bloqueo especificado no puede ser mayor que cero cuando se llama a la función. C26111 de advertencia se emite cuando se produce un error en una función liberar el bloqueo antes de llamar a otra función.

## <a name="example"></a>Ejemplo
 En el ejemplo siguiente genera la advertencia C26111 porque la `_Requires_lock_not_held_` se infringe la condición previa al llamar a `DoNotLock` dentro de la sección bloqueada.

```

typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}
```