---
title: C28198
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: b62f6a9fb1e4c78416f77120f5c25fd642b4d124
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/15/2020
ms.locfileid: "77264053"
---
# <a name="c28198"></a>C28198
ADVERTENCIA C28198: posiblemente pérdida de memoria debido a una excepción.

 Esta advertencia indica que no se libera memoria asignada después de que se produzca una excepción. La instrucción al final de la ruta de acceso puede producir una excepción. La memoria se pasó a una función que podría haber guardado una copia que se va a liberar más adelante.

 Esta advertencia es muy similar a la advertencia [C28197](../code-quality/c28197.md). Las anotaciones que se recomiendan para su uso con [C28197](../code-quality/c28197.md) de advertencia también se pueden usar aquí.

## <a name="example"></a>Ejemplo
 El siguiente código de ejemplo genera esta advertencia:

```cpp
char *p1 = new char[10];
char *p2 = new char[10];

test(p1);   // does not save a copy of p

delete[] p2;
delete[] p1;
```

 El siguiente código de ejemplo evita esta advertencia:

```cpp
char *p1 = new char[10];
char *p2 = NULL;

test(p1);   // does not save a copy of p
try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
```
