---
title: C28198
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 0867c088e4bfb01a6b1ba9eeb75a7dc91c1321b5
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 12/06/2019
ms.locfileid: "74878884"
---
# <a name="c28198"></a>C28198
Advertencia C28198: Posible pérdida de memoria debido a una excepción

 Esta advertencia indica que no se libera memoria asignada después de que se produzca una excepción. La instrucción al final de la ruta de acceso puede producir una excepción. La memoria se pasó a una función que podría haber guardado una copia que se va a liberar más adelante.

 Esta advertencia es muy similar a la advertencia [C28197](../code-quality/c28197.md). Las anotaciones que se recomiendan para su uso con [C28197](../code-quality/c28197.md) de advertencia también se pueden usar aquí.

## <a name="example"></a>Ejemplo
 El siguiente código de ejemplo genera esta advertencia:

```cpp
char *p1 = new char[10];
char *p2 = new char[10];

test(p1);   // does not save a copy of p

delete[] p2;
delete[] p1;
```

 El siguiente código de ejemplo evita esta advertencia:

```cpp
char *p1 = new char[10];
char *p2 = NULL;

test(p1);   // does not save a copy of p
try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
```
