---
title: C6255
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6255
helpviewer_keywords:
- C6255
ms.assetid: bb6430b2-782a-4410-a8e1-609df06007de
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 3c36467e8bc40d0fe4bae1ea71a19fdaf0a8eecc
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/15/2020
ms.locfileid: "77267501"
---
# <a name="c6255"></a>C6255
Advertencia C6255: _alloca indica un error iniciando una excepción de desbordamiento de pila. Considere utilizar _malloca_s en su lugar.

 Esta advertencia indica que se ha detectado una llamada a `_alloca` fuera del control de excepciones local. Siempre se debe llamar a `_alloca` desde el ámbito protegido de un controlador de excepciones, porque puede iniciar una excepción de desbordamiento de pila en caso de error. Si es posible, en lugar de utilizar `_alloca`, considere utilizar `_malloca`, que es una versión más segura de `_alloca`.

## <a name="example"></a>Ejemplo
 El código siguiente genera esta advertencia porque `_alloca` puede generar la excepción:

```cpp
#include <windows.h>

void f( )
{
  void *p = _alloca(10);
  // code ...
}
```

 Para corregir esta advertencia, utilice `_malloca` y agregue un controlador de excepciones como se muestra en el código siguiente:

```cpp
#include <windows.h>
#include <malloc.h>

void f( )
{
  void *p;
  int errcode;
  __try
  {
    p = _malloca(10);
    // code...
    _freea(p);
  }
  __except( (GetExceptionCode() == STATUS_STACK_OVERFLOW ) ?
              EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    errcode = _resetstkoflw();
    // code ...
  }
}
```

## <a name="see-also"></a>Vea también
 [_malloca](/cpp/c-runtime-library/reference/malloca)
