---
title: C6312
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 48f18934d1bf78a1764bd3ac7a7c8b7b64508ece
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 10/07/2019
ms.locfileid: "72017761"
---
# <a name="c6312"></a>C6312
C6312 de ADVERTENCIA: Posible bucle infinito: uso de la constante EXCEPTION_CONTINUE_EXECUTION en la expresión de filtro de excepciones de try-except

 Esta advertencia indica el uso de la constante `EXCEPTION_CONTINUE_EXECUTION` (u otra constante que se evalúa como-1) en la expresión de filtro de un controlador de excepciones estructurado. El uso del valor constante `EXCEPTION_CONTINUE_EXECUTION` podría provocar un bucle infinito. Por ejemplo, si el hardware ha generado una excepción, se reiniciará la instrucción que produjo la excepción. Si la dirección que causó la excepción sigue siendo incorrecta, se producirá otra excepción y se controlará de la misma manera. Esto produce un bucle infinito.

 Una llamada explícita a `RaiseException` no producirá directamente un bucle infinito, pero seguirá la ejecución del código en el bloque protegido. Esto puede ser inesperado y podría provocar un bucle infinito si se usaba `RaiseException` para evitar desreferenciar un puntero no válido.

 Normalmente, `EXCEPTION_CONTINUE_EXECUTION` solo debe ser devuelto por una función llamada en la expresión de filtro, que tiene la oportunidad de corregir el puntero que produjo la excepción o la memoria subyacente.

## <a name="example"></a>Ejemplo
 El código siguiente genera esta advertencia:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 Para corregir esta advertencia, utilice el código siguiente:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```