---
title: 'CA2124: Incluir cláusulas Finally vulnerables en un bloque Try externo'
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
helpviewer_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
ms.assetid: 82efd224-9e60-4b88-a0f5-dfabcc49a254
author: mikejo5000
ms.author: mikejo
manager: jillfra
ms.workload:
- multiple
ms.openlocfilehash: d9a7e00e394a5ceb6a5cc111448f8a0aba5925ad
ms.sourcegitcommit: f3f668ecaf11b4c2738ebc91923c6b5e38e74670
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 01/16/2020
ms.locfileid: "76112332"
---
# <a name="ca2124-wrap-vulnerable-finally-clauses-in-outer-try"></a>CA2124: Incluir cláusulas Finally vulnerables en un bloque Try externo

|||
|-|-|
|TypeName|WrapVulnerableFinallyClausesInOuterTry|
|Identificador de comprobación|CA2124|
|Categoría|Microsoft.Security|
|Cambio importante|Poco problemático|

## <a name="cause"></a>Motivo
En las versiones 1,0 y 1,1 del .NET Framework, un método público o protegido contiene un `try`/`catch`/bloque `finally`. El bloque `finally` parece restablecer el estado de seguridad y no se incluye en un bloque de `finally`.

> [!NOTE]
> Esta regla heredada no está disponible en los analizadores de FxCop. Para obtener más información, consulte [reglas en desuso](fxcop-rule-port-status.md#deprecated-rules).

## <a name="rule-description"></a>Descripción de la regla
Esta regla localiza `try`bloques de `finally` de /en código destinado a las versiones 1,0 y 1,1 del .NET Framework que podrían ser vulnerables a los filtros de excepciones malintencionados presentes en la pila de llamadas. Si se producen operaciones confidenciales como la suplantación en el bloque try y se produce una excepción, el filtro se puede ejecutar antes que el bloque `finally`. En el ejemplo de suplantación, esto significa que el filtro se ejecutaría como el usuario suplantado. Los filtros solo se pueden implementar en Visual Basic.

> [!NOTE]
> En las versiones 2,0 y posteriores del .NET Framework, el motor en tiempo de ejecución protege automáticamente un `try`/`catch`/ bloque `finally` de los filtros de excepciones malintencionados, si el restablecimiento se produce directamente en el método que contiene el bloque de excepción.

## <a name="how-to-fix-violations"></a>Cómo corregir infracciones
Coloque el `try`desencapsulado /`finally` en un bloque try externo. Vea el segundo ejemplo siguiente. Esto obliga a que se ejecute el `finally` antes de filtrar el código.

## <a name="when-to-suppress-warnings"></a>Cuándo suprimir advertencias
No suprima las advertencias de esta regla.

## <a name="pseudo-code-example"></a>Ejemplo de pseudocódigo

### <a name="description"></a>Descripción

El pseudocódigo siguiente muestra el patrón que detecta esta regla.

```csharp
try {
   // Do some work.
   Impersonator imp = new Impersonator("John Doe");
   imp.AddToCreditCardBalance(100);
}
finally {
   // Reset security state.
   imp.Revert();
}
```

En el siguiente pseudocódigo se muestra el patrón que puede usar para proteger el código y satisfacer esta regla.

```csharp
try {
     try {
        // Do some work.
     }
     finally {
        // Reset security state.
     }
}
catch()
{
    throw;
}
```
