---
title: 'CA2124: Incluir cláusulas finally vulnerables en un bloque try externo'
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
helpviewer_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
ms.assetid: 82efd224-9e60-4b88-a0f5-dfabcc49a254
author: gewarren
ms.author: gewarren
manager: jillfra
ms.workload:
- multiple
ms.openlocfilehash: 0008767f7d37e2c088dad58a328b025f81090ad8
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 10/07/2019
ms.locfileid: "72021790"
---
# <a name="ca2124-wrap-vulnerable-finally-clauses-in-outer-try"></a>CA2124: Incluir cláusulas finally vulnerables en un bloque try externo

|||
|-|-|
|TypeName|WrapVulnerableFinallyClausesInOuterTry|
|Identificador de comprobación|CA2124|
|Category|Microsoft.Security|
|Cambio importante|Poco problemático|

## <a name="cause"></a>Motivo
En las versiones 1,0 y 1,1 del .NET Framework, un método público o protegido contiene un bloque `try` @ no__t-1 @ no__t-2 @ no__t-3 @ no__t-4. El bloque `finally` parece restablecer el estado de seguridad y no está incluido en un bloque `finally`.

## <a name="rule-description"></a>Descripción de la regla
Esta regla busca los bloques `try` @ no__t-1 @ no__t-2 en el código que tiene como destino las versiones 1,0 y 1,1 del .NET Framework que podrían ser vulnerables a los filtros de excepciones malintencionados presentes en la pila de llamadas. Si se producen operaciones confidenciales como la suplantación en el bloque try y se produce una excepción, el filtro se puede ejecutar antes que el bloque `finally`. En el ejemplo de suplantación, esto significa que el filtro se ejecutaría como el usuario suplantado. Los filtros solo se pueden implementar en Visual Basic.

> [!NOTE]
> En las versiones 2,0 y posteriores del .NET Framework, el motor en tiempo de ejecución protege automáticamente un bloque `try` @ no__t-1 @ no__t-2 @ no__t-3 @ no__t-4 de los filtros de excepciones malintencionados, si el restablecimiento se produce directamente en el método que contiene el bloque de excepción.

## <a name="how-to-fix-violations"></a>Cómo corregir infracciones
Coloque el @no__t desencapsulado-0 @ no__t-1 @ no__t-2 en un bloque try externo. Vea el segundo ejemplo siguiente. Esto obliga a que se ejecute `finally` antes de filtrar el código.

## <a name="when-to-suppress-warnings"></a>Cuándo suprimir advertencias
No suprima las advertencias de esta regla.

## <a name="pseudo-code-example"></a>Ejemplo de pseudocódigo

### <a name="description"></a>Descripción

El pseudocódigo siguiente muestra el patrón que detecta esta regla.

```csharp
try {
   // Do some work.
   Impersonator imp = new Impersonator("John Doe");
   imp.AddToCreditCardBalance(100);
}
finally {
   // Reset security state.
   imp.Revert();
}
```

En el siguiente pseudocódigo se muestra el patrón que puede usar para proteger el código y satisfacer esta regla.

```csharp
try {
     try {
        // Do some work.
     }
     finally {
        // Reset security state.
     }
}
catch()
{
    throw;
}
```