---
title: 'CA3004: Revisión de código en busca de vulnerabilidades de divulgación de información'
ms.date: 04/03/2019
ms.topic: reference
author: dotpaul
ms.author: paulming
manager: jillfra
dev_langs:
- CSharp
- VB
ms.workload:
- multiple
ms.openlocfilehash: 4965c9df3c2256511b8e44de8d388a9155d0d8f9
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 10/07/2019
ms.locfileid: "72021280"
---
# <a name="ca3004-review-code-for-information-disclosure-vulnerabilities"></a>CA3004: Revisión de código en busca de vulnerabilidades de divulgación de información

|||
|-|-|
|TypeName|ReviewCodeForInformationDisclosureVulnerabilities|
|Identificador de comprobación|CA3004|
|Category|Microsoft.Security|
|Cambio importante|Poco problemático|

## <a name="cause"></a>Motivo

El mensaje de una excepción, el seguimiento de la pila o la representación de cadena alcanza la salida Web.

## <a name="rule-description"></a>Descripción de la regla

Al revelar la información de la excepción, se ofrece a los atacantes información sobre el funcionamiento interno de la aplicación, lo que puede ayudar a los atacantes a encontrar otras vulnerabilidades que se puedan aprovechar.

Esta regla intenta buscar un mensaje de excepción, un seguimiento de la pila o una representación de cadena que se envía a una respuesta HTTP.

> [!NOTE]
> Esta regla no puede realizar el seguimiento de los datos entre ensamblados. Por ejemplo, si un ensamblado detecta una excepción y, a continuación, la pasa a otro ensamblado que genera la excepción, esta regla no generará una advertencia.

> [!NOTE]
> Existe un límite configurable en cuanto a la profundidad con que esta regla analizará el flujo de datos a través de las llamadas a métodos. Vea [configuración del analizador](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#dataflow-analysis) para saber cómo configurar el límite en un archivo EditorConfig.

## <a name="how-to-fix-violations"></a>Cómo corregir infracciones

No genere información de excepción en las respuestas HTTP. En su lugar, proporcione un mensaje de error genérico. Consulte [la página de control de errores de OWASP](https://www.owasp.org/index.php/Error_Handling) para obtener más información.

## <a name="when-to-suppress-warnings"></a>Cuándo suprimir advertencias

Si sabe que la salida web está dentro del límite de confianza de la aplicación y nunca se expone fuera, es correcto suprimir esta advertencia. Esto no es habitual. Tenga en cuenta que el límite de confianza de la aplicación y los flujos de datos pueden cambiar con el tiempo.

## <a name="pseudo-code-examples"></a>Ejemplos de pseudocódigo

### <a name="violation"></a>Infracción

```csharp
using System;

public partial class WebForm : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs eventArgs)
    {
        try
        {
            object o = null;
            o.ToString();
        }
        catch (Exception e)
        {
            this.Response.Write(e.ToString());
        }
    }
}
```

```vb
Imports System

Partial Public Class WebForm
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(sender As Object, eventArgs As EventArgs)
        Try
            Dim o As Object = Nothing
            o.ToString()
        Catch e As Exception
            Me.Response.Write(e.ToString())
        End Try
    End Sub
End Class
```

### <a name="solution"></a>Solución

```csharp
using System;

public partial class WebForm : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs eventArgs)
    {
        try
        {
            object o = null;
            o.ToString();
        }
        catch (Exception e)
        {
            this.Response.Write("An error occurred. Please try again later.");
        }
    }
}
```

```vb
Imports System

Partial Public Class WebForm
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(sender As Object, eventArgs As EventArgs)
        Try
            Dim o As Object = Nothing
            o.ToString()
        Catch e As Exception
            Me.Response.Write("An error occurred. Please try again later.")
        End Try
    End Sub
End Class
```